### PR TITLE
able to view room name for device(s)

### PR DESCRIPTION
**Pull request by 10der**
for easy sorting devices by room in HomeKit app I can propose to add a room name to device name

### CODE REVIEW

**Comment by 10der** [comment]
@ilcato ping.

**Comment by ilcato** [comment]
I'm not in favor of this change. Maybe you can add an option to enable it and by default it will be disabled. What do you think?

**Comment by odenisenko** [comment]
> I'm not in favor of this change. Maybe you can add an option to enable it and by default it will be disabled. What do you think?
yep! sure! you right!
please do not hesitate to use the reply button instead of silence :)

**Comment by ilcato** [comment]
@10der comma missing in the example

**Comment by ilcato** [comment]
@10der published in 1.06 can you test it?

**Pull request merged**
